name: fdr
description: "Fully declarative routing for Flutter applications, as easy as `Widget.build`."
version: 0.0.5
homepage: "https://github.com/relentless-works/fdr"
repository: "https://github.com/relentless-works/fdr"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  golden_toolkit: ^0.15.0

flutter:
