name: fdr
description: "Fully declarative routing for Flutter applications."
version: 0.0.1
homepage: "https://github.com/relentless-works/fdr"
repository: "https://github.com/relentless-works/fdr"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
